name: code_generation_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.12.0
  cupertino_icons: ^0.1.3
  json_serializable: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  freezed: ^0.12.0

flutter:
  uses-material-design: true
